name: deploy tsoobame
on:
  workflow_dispatch:
  push:
    branch:
      - main

jobs:
  cancel-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        # Use the latest version of gengo
      - name: Install gengo
        run: |
          curl -fsSL https://raw.githubusercontent.com/saasuke-labs/gengo/main/install/install.sh | bash
          gengo version
      - name: Generate site
        run: |
          gengo generate --manifest gengo.yaml --output dist --plain
        # There is no proper home page, so for now we just copy the "blog" index as the home page
      - name: Temp - Use blog index as home page
        run: |
          cp dist/blog/index.html dist/index.html
      - name: Push to tsoobame repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: "dist"
          destination-github-username: "tsoobame"
          destination-repository-name: "tsoobame.github.io"
          user-email: ${{ secrets.SSH_KEY_EMAIL }}
          target-branch: main
